### ISSUE TITLE
Cannot find name 'mtcaptchaConfig' and Cannot find name 'mtcaptcha'

### ISSUE THREAD

**Issue by Pierre-Brogard** [mtcaptcha-public/mtcaptcha-angularjs-example#1]
Hi,

I have forked, configured (site key) and started the project with npm (install and start), i got 3 errors. The App doesn't reconize some variables : 

1 - fake-backend.ts :
TS2304: Cannot find name 'mtcaptcha' (42,32)
TS2304: Cannot find name 'mtcaptcha' (60,32)

2 - login.component.ts : 
TS2304: Cannot find name 'mtcaptcha' (34,9)
TS2304: Cannot find name 'mtcaptchaConfig' (34,44)

3 - register.component.ts
TS2304: Cannot find name 'mtcaptcha' (35,9)
TS2304: Cannot find name 'mtcaptchaConfig' (35,44)

Can you help me please ? Any ideas ?

**Comment by batou-mtcapthca** [comment]
Hi @Pierre-Brogard 
Thank you for reporting the issue, this issue is fixed now.  Please get the latest code, it should work.
